// Generated by CoffeeScript 1.9.2
(function() {
  var net, server;

  net = require('net');

  server = net.createServer(function(socket) {
    var dates, dt;
    dt = new Date();
    dates = [dt.getFullYear(), dt.getMonth() + 1, dt.getDate(), dt.getHours(), dt.getMinutes()].map(function(value) {
      if (value < 10) {
        return '0' + value;
      } else {
        return '' + value;
      }
    });
    return socket.end(dates[0] + "-" + dates[1] + "-" + dates[2] + " " + dates[3] + ":" + dates[4] + "\n");
  });

  server.listen(process.argv[2]);

}).call(this);
