// Generated by CoffeeScript 1.9.2
(function() {
  var fs, http, server;

  http = require('http');

  fs = require('fs');

  server = http.createServer(function(req, res) {
    return fs.createReadStream(process.argv[3]).pipe(res);
  });

  server.listen(process.argv[2]);

}).call(this);
