// Generated by CoffeeScript 1.9.2
(function() {
  var http, map, server;

  http = require('http');

  map = require('through2-map');

  server = http.createServer(function(req, res) {
    if (req.method !== 'POST') {
      res.end('send me a POST\n');
    }
    return req.pipe(map(function(stream) {
      return stream.toString().toUpperCase();
    })).pipe(res);
  });

  server.listen(process.argv[2]);

}).call(this);
