// Generated by CoffeeScript 1.9.2
(function() {
  var http, parsetime, server, unixtime, url;

  http = require('http');

  url = require('url');

  parsetime = function(time) {
    return {
      hour: time.getHours(),
      minute: time.getMinutes(),
      second: time.getSeconds()
    };
  };

  unixtime = function(time) {
    return {
      unixtime: time.getTime()
    };
  };

  server = http.createServer(function(req, res) {
    var reqUrl, result, time;
    if (req.method === 'POST') {
      res.end('send me a POST\n');
    }
    reqUrl = url.parse(req.url, true);
    time = new Date(reqUrl.query.iso);
    if (reqUrl.pathname === '/api/parsetime') {
      result = parsetime(time);
    }
    if (reqUrl.pathname === '/api/unixtime') {
      result = unixtime(time);
    }
    if (result) {
      res.writeHead(200, {
        'content-type': 'application/json'
      });
      return res.end(JSON.stringify(result));
    } else {
      res.writeHead(404);
      return res.end();
    }
  });

  server.listen(process.argv[2]);

}).call(this);
