// Generated by CoffeeScript 1.9.2
(function() {
  var fs;

  fs = require('fs');

  fs.readFile(process.argv[2], 'utf8', function(err, data) {
    err && (function() {
      throw new Error(err.stack);
    })();
    return console.log(data.split('\n').length - 1);
  });

}).call(this);
