// Generated by CoffeeScript 1.9.2
(function() {
  var fs, path;

  fs = require('fs');

  path = require('path');

  module.exports = function(dir, ext, callback) {
    return fs.readdir(dir, function(err, files) {
      if (err) {
        return callback(err);
      }
      return callback(null, files.filter(function(file) {
        return path.extname(file) === ('.' + ext);
      }));
    });
  };

}).call(this);
