// Generated by CoffeeScript 1.9.2
(function() {
  var http;

  http = require('http');

  http.get(process.argv[2], function(response) {
    response.setEncoding('utf8');
    return response.on('data', console.log);
  });

}).call(this);
