// Generated by CoffeeScript 1.9.2
(function() {
  var http;

  http = require('http');

  http.get(process.argv[2], function(response) {
    var data;
    data = '';
    response.setEncoding('utf8');
    response.on('data', function(stream) {
      return data += stream;
    });
    return response.on('end', function() {
      console.log(data.length);
      return console.log(data);
    });
  });

}).call(this);
