// Generated by CoffeeScript 1.9.2
(function() {
  var contents, count, http, urls;

  http = require('http');

  urls = process.argv.slice(2, 5);

  contents = [];

  count = 0;

  urls.map(function(url) {
    return http.get(url, function(res) {
      var content;
      res.setEncoding('utf8');
      content = '';
      res.on('data', function(stream) {
        return content += stream;
      });
      return res.on('end', function() {
        var i, len, results;
        contents[urls.indexOf(url)] = content;
        count++;
        if (count === 3) {
          results = [];
          for (i = 0, len = contents.length; i < len; i++) {
            content = contents[i];
            results.push(console.log(content));
          }
          return results;
        }
      });
    });
  });

}).call(this);
